#:schema https://www.schemastore.org/pyproject.json
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "{{ cookiecutter.package_name }}"
dynamic = ["version"]
description = "{{ cookiecutter.project_short_description }}"
readme = "README.md"
requires-python = ">={{ cookiecutter.minimum_python_version }}"
license = "MIT"
keywords = []
authors = [
  { name = "{{ cookiecutter.full_name }}", email = "{{ cookiecutter.email }}" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  {%- set python_start = (cookiecutter.minimum_python_version.split('.')[-1] | int) %}
  {%+ for item in range(python_start, 15) -%}
  "Programming Language :: Python :: 3.{{ item }}",
  {%+ endfor -%}
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
]

[project.optional-dependencies]

[dependency-groups]
dev = [
  { include-group = "test" },
  { include-group = "types" },
]
test = [
  "pytest",
  "tomli ; python_version < '3.11'",
]
types = [
  { include-group = "test" },
  "typing-extensions",
]
type-checkers = [
  { include-group = "types" },
  "basedpyright",
  "pyrefly",
  "pyright[nodejs]",
  "ty",
  "zuban",
]
docs = [
  "zensical",
]

[project.urls]
Documentation = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.package_name }}#readme"
Issues = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.package_name }}/issues"
Source = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.package_name }}"

[project.scripts]
{{ cookiecutter.package_name }} = "{{ cookiecutter.module_name }}.__main__:main"

###############################################################################
# region: hatch
###############################################################################
[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/{{ cookiecutter.module_name }}/_version.py"
{%- if cookiecutter.module_name != cookiecutter.package_name.replace('-', '_') %}

[tool.hatch.build.targets.wheel]
packages = [
  "src/{{ cookiecutter.module_name }}",
]
{%- endif %}

[tool.hatch.envs.hatch-test]
dependency-groups = [
  "test",
]

[tool.hatch.envs.types]
dependency-groups = [
  "types",
]

[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/{{ cookiecutter.module_name }} tests}"

[[tool.hatch.envs.hatch-test.matrix]]
python = [
  {%- set python_start = (cookiecutter.minimum_python_version.split('.')[-1] | int) %}
  {%- for item in range(python_start, 15) %}
  "3.{{ item }}",
  {%- endfor %}
]
###############################################################################
# endregion: hatch
###############################################################################

###############################################################################
# region: coverage
###############################################################################
[tool.coverage.run]
source_pkgs = ["{{ cookiecutter.module_name }}", "tests"]
branch = true
parallel = true
omit = [
]

[tool.coverage.paths]
{{ cookiecutter.module_name }} = ["src/{{ cookiecutter.module_name }}"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
###############################################################################
# endregion: coverage
###############################################################################

###############################################################################
# region: ruff
###############################################################################
[tool.hatch.envs.hatch-static-analysis]
config-path = "none"

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
  "ALL",
]
ignore = [
  "COM812",  # missing-trailing-comma
  "D",       # pydocstyle
  "ERA001",  # commented-out-code
  "EXE003",  # shebang-missing-python
  "ISC001",  # single-line-implicit-string-concatenation
  "PTH",     # flake8-use-pathlib
  "T20",     # flake8-print
  "PLC0415", # import-outside-top-level
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 100

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
  "S101",
]
###############################################################################
# endregion: ruff
###############################################################################

###############################################################################
# region: type-checkers
###############################################################################
[tool.mypy]
# https://mypy.readthedocs.io/en/stable/config_file.html
strict = true

[tool.zuban]
# https://docs.zubanls.com/en/latest/usage.html#configuration
mode = "default"
strict = true

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
typeCheckingMode = "strict"
reportUnusedImport = false

# [tool.basedpyright]
# # https://docs.basedpyright.com/latest/configuration/config-files/
# typeCheckingMode = "all"

[tool.pyrefly]
# https://pyrefly.org/en/docs/configuration/
preset = "strict"

[tool.ty.rules]
# https://docs.astral.sh/ty/reference/configuration/
all = "error"
###############################################################################
# endregion: type-checkers
###############################################################################
