name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python:
        {%- set python_start = (cookiecutter.minimum_python_version.split('.')[-1] | int) %}
        {%- for item in range(python_start, 14) %}
          - "3.{{ item }}"
        {%- endfor %}
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ "{{" }} matrix.platform {{ "}}" }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ "{{" }} matrix.python {{ "}}" }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ "{{" }} matrix.python {{ "}}" }}
      - name: Install test dependencies
        run: python -m pip install --upgrade hatch
      - name: Test
        run: hatch test --python=${{ "{{" }} matrix.python {{ "}}" }}
